export const FETCH_ITEMS_REQUEST = 'FETCH_ITEMS_REQUEST';
export const FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS';
export const FETCH_ITEMS_FAILURE = 'FETCH_ITEMS_FAILURE';

export const FETCH_FAVOURITES_REQUEST = 'FETCH_FAVOURITES_REQUEST';
export const FETCH_FAVOURITES_SUCCESS = 'FETCH_FAVOURITES_SUCCESS';
export const FETCH_FAVOURITES_FAILURE = 'FETCH_FAVOURITES_FAILURE';

export const UPDATE_FAVOURITE_REQUEST = 'UPDATE_FAVOURITE_REQUEST';
export const UPDATE_FAVOURITE_SUCCESS = 'UPDATE_FAVOURITE_SUCCESS';
export const UPDATE_FAVOURITE_FAILURE = 'UPDATE_FAVOURITE_FAILURE';
